# Generated by Django 5.0.6 on 2024-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_investplace_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investplace",
            name="heat_supply",
            field=models.CharField(
                choices=[
                    ("Да", "Yes"),
                    ("Нет", "No"),
                    ("Возможно создание", "Ability"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="investplace",
            name="surveying",
            field=models.BooleanField(null=True, verbose_name="Межевание ЗУ"),
        ),
    ]
