# Generated by Django 5.0.6 on 2024-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_investplace_heat_supply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investplace",
            name="owner_inn",
            field=models.CharField(max_length=12),
        ),
    ]
