# Generated by Django 5.0.6 on 2024-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_investplace_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investplace",
            name="owner_inn",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
