# Generated by Django 5.0.6 on 2024-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_investplace_owner_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investplace",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
