# Generated by Django 5.0.6 on 2024-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_investplace_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="name_of_the_responsible_authority",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="support_level",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
