# Generated by Django 5.0.6 on 2024-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_regionalsupportsmeasures_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalsupportsmeasures",
            name="support_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
