# Generated by Django 5.0.6 on 2024-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_regionalsupportsmeasures_support_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="required_documents",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
