# Generated by Django 5.0.6 on 2024-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_regionalsupportsmeasures_required_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="required_documents",
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
