# Generated by Django 5.0.6 on 2024-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_regionalsupportsmeasures_required_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="application_procedure",
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="requirements_for_the_applicant",
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
