# Generated by Django 5.0.6 on 2024-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_regionalsupportsmeasures_application_procedure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="okved",
            field=models.CharField(max_length=16000, null=True),
        ),
    ]
