# Generated by Django 5.0.6 on 2024-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_regionalsupportsmeasures_okved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="requirements_for_the_applicant",
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
