# Generated by Django 5.0.6 on 2024-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_regionalsupportsmeasures_required_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="main_idea",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="regionalsupportsmeasures",
            name="npa_requisite",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
