# Generated by Django 5.0.6 on 2024-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_specialeconomicszonesandtechn_validation_period_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialeconomicszonesandtechn",
            name="minimal_rental_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="specialeconomicszonesandtechn",
            name="total_area",
            field=models.FloatField(null=True),
        ),
    ]
