# Generated by Django 5.0.6 on 2024-06-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_specialeconomicszonesandtechn_minimal_rental_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialeconomicszonesandtechn',
            options={'verbose_name': 'Специальные экономические зоны?'},
        ),
    ]
