# Generated by Django 4.2.13 on 2024-06-11 07:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistentThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тема ассистента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Тема активная?')),
            ],
            options={
                'verbose_name': 'Тема ассистента',
                'verbose_name_plural': 'Темы ассистента',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ветка сообщения активна?')),
                ('message', ckeditor.fields.RichTextField(null=True, verbose_name='Текст сообщения')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistent_app.assistentthememodel')),
            ],
            options={
                'verbose_name': 'Сообщение ассистента',
                'verbose_name_plural': 'Сообщения ассистента',
            },
        ),
    ]
