# Generated by Django 4.2.13 on 2024-06-11 09:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='is_filter_question',
            field=models.BooleanField(default=True, verbose_name='Вопрос на фильтрацию товаров'),
        ),
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistent_app.assistentthememodel', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='FilterFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='Поле для фильтрации')),
                ('many', models.BooleanField(default=False, verbose_name='Посылается множетсво значений?')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_app.chatmessagemodel')),
            ],
            options={
                'verbose_name': 'Фильтрация',
            },
        ),
    ]
