# Generated by Django 4.2.13 on 2024-06-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_app', '0002_chatmessagemodel_is_filter_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterfields',
            name='choices',
            field=models.TextField(blank=True, help_text='Напишите каждый пункт на новой строке', null=True, verbose_name='Пункты для выбора'),
        ),
    ]
