# Generated by Django 4.2.13 on 2024-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_app', '0003_filterfields_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='is_filter_question',
            field=models.BooleanField(default=False, verbose_name='Вопрос на фильтрацию товаров'),
        ),
    ]
