# Generated by Django 5.0.6 on 2024-06-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_app', '0005_remove_filterfields_chat_message_filterconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterfields',
            old_name='model_class',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='filterfields',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='filterfields',
            name='many',
        ),
    ]
