# Generated by Django 5.0.6 on 2024-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisation_sector",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Отрасль деятельности",
            ),
        ),
    ]
